### ISSUE TITLE
pip install faileed

### ISSUE THREAD

**Issue by CJAclines** [willcodefortea/filewatch#2]
after running `pip install filewatch` I received errors
```
collecting filewatch
  Using cached filewatch-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3bt2v6ff/filewatch/setup.py", line 5, in <module>
        from filewatch import VERSION
      File "/tmp/pip-build-3bt2v6ff/filewatch/filewatch/__init__.py", line 5, in <module>
        from filewatch.watcher import Watcher
      File "/tmp/pip-build-3bt2v6ff/filewatch/filewatch/watcher.py", line 6, in <module>
        from filewatch.config import settings
      File "/tmp/pip-build-3bt2v6ff/filewatch/filewatch/config.py", line 1, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3bt2v6ff/filewatch/

```

**Comment by xuniuer** [comment]
It works by `pip install filewatch` on Ubuntu 18.04 with python 2.7. 
The above errors are reported when using python 3 environment.
